# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(80, 220, 93, 28))
        self.cancel.setObjectName("cancel")
        self.gencode = QtWidgets.QPushButton(Dialog)
        self.gencode.setGeometry(QtCore.QRect(230, 220, 93, 28))
        self.gencode.setObjectName("gencode")
        self.tablename_label = QtWidgets.QLabel(Dialog)
        self.tablename_label.setGeometry(QtCore.QRect(70, 70, 61, 16))
        self.tablename_label.setObjectName("tablename_label")
        self.tablename_line = QtWidgets.QLineEdit(Dialog)
        self.tablename_line.setGeometry(QtCore.QRect(150, 70, 171, 21))
        self.tablename_line.setObjectName("tablename_line")
        self.packagename_label = QtWidgets.QLabel(Dialog)
        self.packagename_label.setGeometry(QtCore.QRect(70, 100, 61, 16))
        self.packagename_label.setObjectName("packagename_label")
        self.packagename_line = QtWidgets.QLineEdit(Dialog)
        self.packagename_line.setGeometry(QtCore.QRect(150, 100, 171, 21))
        self.packagename_line.setObjectName("packagename_line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancel.setText(_translate("Dialog", "取消"))
        self.gencode.setText(_translate("Dialog", "生成"))
        self.tablename_label.setText(_translate("Dialog", "表名:"))
        self.packagename_label.setText(_translate("Dialog", "包名:"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())